# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\"\x1a\n\x07\x43ommand\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"$\n\x0cNotification\x12\x14\n\x0cnotification\x18\x01 \x01(\t\",\n\x07Message\x12!\n\x0bTextMessage\x18\x01 \x01(\x0b\x32\x0c.TextMessage\"\x1b\n\x0bTextMessage\x12\x0c\n\x04text\x18\x01 \x01(\t\"[\n\x03\x41\x43K\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x13\n\x0bgmt_created\x18\x03 \x01(\t\x12\x12\n\nori_msg_id\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\"\xcf\x02\n\tIMMessage\x12\r\n\x05token\x18\x01 \x01(\t\x12\x1e\n\x08msg_type\x18\x02 \x01(\x0e\x32\x0c.MessageType\x12\x0e\n\x06msg_id\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t\x12\r\n\x05_from\x18\x05 \x01(\t\x12\x0b\n\x03_to\x18\x06 \x01(\t\x12\x11\n\ttimestamp\x18\x07 \x01(\x03\x12\x10\n\x08platform\x18\x08 \x01(\t\x12\x1e\n\x07\x63ommand\x18\t \x01(\x0b\x32\x08.CommandH\x00\x88\x01\x01\x12(\n\x0cnotification\x18\n \x01(\x0b\x32\r.NotificationH\x01\x88\x01\x01\x12\x1e\n\x07message\x18\x0b \x01(\x0b\x32\x08.MessageH\x02\x88\x01\x01\x12\x16\n\x03\x61\x63k\x18\x0c \x01(\x0b\x32\x04.ACKH\x03\x88\x01\x01\x42\n\n\x08_commandB\x0f\n\r_notificationB\n\n\x08_messageB\x06\n\x04_ack*M\n\x0bMessageType\x12\x11\n\rSystemMessage\x10\x00\x12\x13\n\rIMTextMessage\x10\xb1\xea\x01\x12\x16\n\x10IMTextMessageAck\x10\xb2\xea\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MESSAGETYPE']._serialized_start=589
  _globals['_MESSAGETYPE']._serialized_end=666
  _globals['_COMMAND']._serialized_start=17
  _globals['_COMMAND']._serialized_end=43
  _globals['_NOTIFICATION']._serialized_start=45
  _globals['_NOTIFICATION']._serialized_end=81
  _globals['_MESSAGE']._serialized_start=83
  _globals['_MESSAGE']._serialized_end=127
  _globals['_TEXTMESSAGE']._serialized_start=129
  _globals['_TEXTMESSAGE']._serialized_end=156
  _globals['_ACK']._serialized_start=158
  _globals['_ACK']._serialized_end=249
  _globals['_IMMESSAGE']._serialized_start=252
  _globals['_IMMESSAGE']._serialized_end=587
# @@protoc_insertion_point(module_scope)
